package gameState;

public enum GameState {

	LANGUAGE_MENU,
    START_MENU,
    RUNNING_GAME,
    RUNNING_MULTIPLAYER,
    GAME_OVER,
    INFO_SCREEN,
    PAUSED_GAME,
    GAME_CONTROLS,
    LEVELS_MENU,
    WIN_SCREEN,
    WIN_SCREEN2
}
